### ISSUE TITLE
Downloading is broken

### ISSUE THREAD

**Issue by Corewala** [evan-goode/mania#10]
Attempting to download anything (url, track, artist or album) returns this error:

```
Warning: MQA support is currently broken. Files requested as `master` quality will download as `lossless`.
Authenticating...
Uncaught HTTP Error:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size="1px">\nRequest blocked.\nWe can\'t connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR clear="all">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n<BR clear="all">\n<HR noshade size="1px">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: Y49J2AVA0R1ORyg0ii9vfybH_Wn_NaXG5mQK7YMzqZ8xe9KOKe210Q==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>
```

**Comment by evan-goode** [comment]
Thanks for the issue, sorry for my delayed reply! It's finals season over here. This should be addressed in 842ddc4; I swapped out the old login method for the TV-based login that [RedSea](https://github.com/Dniel97/RedSea) does. I'll merge this to master in the next couple days after I update the README and do a little more testing.

I saw you were writing a GUI, and the new login method unfortunately involves some command-line interactivity, see this function: https://github.com/evan-goode/mania/blob/842ddc441f08aeab1902b0e6f2db1900d3e533f8/mania/tidal.py#L93
Feel free to PR to do this in a more modular way, it would be cool if the back-endish parts of mania could be easily reused with other interfaces.

**Comment by Corewala** [comment]
Nice. I tried testing it out and noticed it requires a HiFi subscription to function (I don't have one). Is this due to the new TV-based login system?

**Comment by evan-goode** [comment]
I commented out the HiFi check in 2897d50, could you give that a try? I copied it over from RedSea without thinking too much about it, but I'm not sure what its purpose is... you would think a non-HiFi account would be able to log in using the same process and fetch lossy tracks. I don't have a non-HiFi account to test :P

**Comment by Corewala** [comment]
Looks like it can download lossy files now. Thanks!

**Comment by Corewala** [comment]
I sent a PR with a change to make the authentication system simpler for external clients.

**Comment by evan-goode** [comment]
> Looks like it can download lossy files now. Thanks!

Sweet! Out of curiosity, what happens when you request a track in lossless or MQA quality? Would be good to show an appropriate error in that case.

**Comment by Corewala** [comment]
```
-> mania url https://tidal.com/browse/track/101982419 --quality lossless

Loaded cached TIDAL session.
Downloading "Never Gonna Give You Up"...
8.23MB [00:01, 5.03MB/s]                                                                                                                                                                                                                      
Resolving metadata...
Skipping Never Gonna Give You Up.flac; received invalid file
Saving TIDAL session for future use...
Done!
```

**Comment by Corewala** [comment]
Oddly enough it does seem to download something, and it is actually playable if you stop mania before it deletes the track. It looks like mania just downloads a high quality lossy track instead.

**Comment by evan-goode** [comment]
Thanks! Yeah, a silent fail is about what I expected. Added a proper error in 83ea107.

**Comment by evan-goode** [comment]
Merged to master.
