### ISSUE TITLE
Download by URL/ID

### ISSUE THREAD

**Issue by ghost** [evan-goode/mania#7]
I'd love support for Tidal URLs, ie 
`mania https://tidal.com/browse/track/140538043` (no need for `lucky` in these cases)

Examples/variants:
```
https://listen.tidal.com/album/140538042
https://tidal.com/browse/album/140538042

https://listen.tidal.com/artist/4332277
https://tidal.com/browse/artist/4332277

https://tidal.com/browse/track/140538043
https://embed.tidal.com/tracks/140538043
```

It looks like tidalapi has direct support for it, if it helps:
```python
tracks = session.get_album_tracks(album_id=16909093)
for track in tracks:
    print(track.name)
```

**Comment by evan-goode** [comment]
Agreed that this would be useful, shouldn't be too hard. I think I'll do an `--id` flag like:

```
mania album --id 140538042
```
and then a separate verb for urls:

```
mania url https://listen.tidal.com/album/140538042
```

**Comment by ghost** [comment]
Amazing, thanks!
